---
download: ~/.ansible-downloads

configure_dotfiles: yes

# https://github.com/ingorichter/dotfiles
dotfiles_repo: ingorichter/dotfiles
dotfiles_dir: "{{ ansible_user_dir }}/.dotfiles"

# Where to drop the downloaded installer.
cargo_tmp: "{{ lookup('env', 'TMPDIR') }}"
cargo_bin: "{{ ansible_user_dir }}/.cargo/bin"
cargo_prefix: "{{ ansible_user_dir }}/.cargo"

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers
  - rs/tap

homebrew_installed_packages:
  - bat
  - curl
  - curlie
  - diff-so-fancy
  - fdupes
  - fzf
  - gnupg
  - go
  - htop
  - hugo
  - jq
  - muesli/tap/duf
  - n
  - newsboat
  - ocrmypdf
  - pdfgrep
  - pinentry-mac
  - pyenv-virtualenv
  - rbenv
  - rg
  - rs/tap/curlie
  - rustup-init
  - shellcheck
  - smartmontools
  - svn
  - teamookla/speedtest/speedtest
  - tmux
  - tree
  - yubikey-personalization
  - zplug
  - zsh

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password6
  - adobe-creative-cloud
  - aerial
  - alacritty
  - alfred
  - alt-tab
  - bitwarden
  - double-commander
  - emacs
  - grammarly
  - handbrake
  - hazel
  - keybase
  - keycastr
  - libreoffice
  - licecap
  - mactex
  - makemkv
  - monitorcontrol
  - nextcloud
  - ngrok
  - nordvpn
  - openscad
  - osxfuse
  - prusaslicer
  - rectangle
  - signal
  - skype
  - sonos
  - sourcetree
  - spotify
  - superduper
  - superproductivity
  - suspicious-package
  - synology-drive
  - telegram-desktop
  - veracrypt
  - visual-studio-code-insiders
  - vivaldi
  - vlc
  - vmware-fusion
  - webstorm
  - webtorrent

mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 1470584107, name: "Dato" }
  - { id: 1176895641, name: "Spark" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 409201541, name: "Xcode" }

pip_packages:
  - name: powerline-shell
    state: present

oh_my_zsh_install: yes
users:
  - username: ingorichter