---
- hosts: all
  become: true
  vars_files:
    - base.config.yml
  roles:
    - base

- hosts: work
  # become_user: ingorichter
  become: false
  vars_files:
    - base.config.yml
  roles:
    - work
    - private

- hosts: personal
  become: false
  vars_files:
    - base.config.yml
  roles:
    - personal
    - private
