---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
    - role: robertdebock.cargo
    - role: gantsign.oh-my-zsh
    - role: private
