---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: robertdebock.cargo
  - name: gantsign.oh-my-zsh
  - name: geerlingguy.dotfiles

collections:
  - name: community.general
  - name: geerlingguy.mac
