- name: Clone rational-emacs repo
  git:
    repo: https://github.com/ingorichter/rational-emacs.git
    dest: ~/.emacs.d/

- name: Install emacs-plus Cask with options
  community.general.homebrew:
    name: emacs-plus@28
    state: present
    install_options: 'with-native-comp,with-mailutils,with-imagemagick'

- name: Link Emacs Binary into /Applications
  ansible.builtin.file:
    src: "{{ homebrew_prefix }}/opt/emacs-plus@28/Emacs.app"
    dest: /Applications/Emacs.app
    state: link
