- name: Install Fonts
  community.general.homebrew_cask:
    name:
      - font-jetbrains-mono
      - font-fira-mono-for-powerline
      - font-fira-mono-for-powerline
      - font-fira-code
      - font-digital-numbers
      - font-consolas-for-powerline
      - font-3270-nerd-font
      - font-3270

    state: present
