- name: Clone dotfiles
  import_tasks: dotfiles.yml
  tags:
  - dotfiles

- name: Install Extras
  import_tasks: extras.yml
  tags:
  - extras


- name: Install Fonts
  import_tasks: fonts.yml
  tags:
  - fonts

- name: Install tmux plugin manager
  import_tasks: tmux-plugin-manager.yml
  tags:
  - tmpm
