- name: Clone dotfiles
  import_tasks: dotfiles.yml
  tags:
  - dotfiles

- name: Install Extras
  import_tasks: extras.yml
  tags:
  - extras

- name: Install tmux plugin manager
  import_tasks: tmux-plugin-manager.yml
  tags:
  - tmpm