- name: Install latest nodejs
  shell: "export N_PREFIX=~/n && n latest"

- name: Update npm to latest version
  shell: "export PATH=$PATH:$N_PREFIX/bin && npm install -g npm"

- name: Install git-split-diffs
  shell: "export PATH=$PATH:$N_PREFIX/bin && npm install -g git-split-diffs"